input: misc: vl53L0: Check VL53L010_get_vcsel_pulse_period() status
VL53L010_get_vcsel_pulse_period() is used without checking its return
value. It looks like it queries hardware, so it is definitely worth
checking.

This fixes the following warning:
drivers/input/misc/vl53L0/src/vl53l010_api.c: In function 'VL53L010_GetMeasurementTimingBudgetMicroSeconds':
drivers/input/misc/vl53L0/src/vl53l010_api.c:2746:47: error: 'CurrentVCSELPulsePeriodPClk' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 2746 |  vcsel_period_reg = (vcsel_period_pclks >> 1) - 1;
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
drivers/input/misc/vl53L0/src/vl53l010_api.c:1087:10: note: 'CurrentVCSELPulsePeriodPClk' was declared here
 1087 |  uint8_t CurrentVCSELPulsePeriodPClk;
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>